environment:
    CCACHE_BASEDIR: $CIRRUS_WORKING_DIR

docker_debian9_task:
  container:
    dockerfile: docker/Dockerfile.debian-9
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip

docker_debian10_task:
  container:
    dockerfile: docker/Dockerfile.debian-10
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip

docker_ubuntu16_task:
  container:
    dockerfile: docker/Dockerfile.ubuntu-16
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip

docker_ubuntu18_task:
  container:
    dockerfile: docker/Dockerfile.ubuntu-18
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip

docker_ubuntu20_task:
  container:
    dockerfile: docker/Dockerfile.ubuntu-20
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip

docker_fedora32_task:
  container:
    dockerfile: docker/Dockerfile.fedora-32
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip

docker_fedora33_task:
  container:
    dockerfile: docker/Dockerfile.fedora-33
    cpu: 4
    memory: 8G
    docker_arguments:
      - SKIP_BUILD: 1

  timeout_in: 120m

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  # Pull tags as well since by default Cirrus CI does not fetch them, but they
  # are needed for `git describe` used in `scripts/autogen-version`. We also
  # pull submodules here.
  update_git_script:
    - git fetch --tags
    - git submodule update --recursive --init

  configure_script:
    - ./configure --generator=Ninja --enable-ccache --prefix=/opt/spicy --with-zeek=/opt/zeek
  build_script:
    - ninja -j5 -C build install
  test_script:
    - cd tests && SPICY_INSTALLATION_DIRECTORY=/opt/spicy btest -a installation -j -d
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy-*.tar.gz
    type: application/gzip
